// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (
    workspace_id,
    project_id,
    ticket_id,
    attempt_id,
    type,
    role,
    name,
    url,
    storage_backend,
    size_bytes,
    mime_type,
    metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, workspace_id, project_id, ticket_id, attempt_id, type, role, name, url, storage_backend, size_bytes, mime_type, metadata, created_at
`

type CreateArtifactParams struct {
	WorkspaceID    pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ProjectID      pgtype.UUID `db:"project_id" json:"project_id"`
	TicketID       pgtype.UUID `db:"ticket_id" json:"ticket_id"`
	AttemptID      pgtype.UUID `db:"attempt_id" json:"attempt_id"`
	Type           string      `db:"type" json:"type"`
	Role           string      `db:"role" json:"role"`
	Name           string      `db:"name" json:"name"`
	Url            string      `db:"url" json:"url"`
	StorageBackend string      `db:"storage_backend" json:"storage_backend"`
	SizeBytes      int64       `db:"size_bytes" json:"size_bytes"`
	MimeType       string      `db:"mime_type" json:"mime_type"`
	Metadata       []byte      `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.TicketID,
		arg.AttemptID,
		arg.Type,
		arg.Role,
		arg.Name,
		arg.Url,
		arg.StorageBackend,
		arg.SizeBytes,
		arg.MimeType,
		arg.Metadata,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TicketID,
		&i.AttemptID,
		&i.Type,
		&i.Role,
		&i.Name,
		&i.Url,
		&i.StorageBackend,
		&i.SizeBytes,
		&i.MimeType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, workspace_id, project_id, ticket_id, attempt_id, type, role, name, url, storage_backend, size_bytes, mime_type, metadata, created_at
FROM artifacts
WHERE id = $1
`

func (q *Queries) GetArtifact(ctx context.Context, id pgtype.UUID) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TicketID,
		&i.AttemptID,
		&i.Type,
		&i.Role,
		&i.Name,
		&i.Url,
		&i.StorageBackend,
		&i.SizeBytes,
		&i.MimeType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifactsByAttempt = `-- name: ListArtifactsByAttempt :many
SELECT id, workspace_id, project_id, ticket_id, attempt_id, type, role, name, url, storage_backend, size_bytes, mime_type, metadata, created_at
FROM artifacts
WHERE attempt_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListArtifactsByAttempt(ctx context.Context, attemptID pgtype.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByAttempt, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.TicketID,
			&i.AttemptID,
			&i.Type,
			&i.Role,
			&i.Name,
			&i.Url,
			&i.StorageBackend,
			&i.SizeBytes,
			&i.MimeType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifactsByTicket = `-- name: ListArtifactsByTicket :many
SELECT id, workspace_id, project_id, ticket_id, attempt_id, type, role, name, url, storage_backend, size_bytes, mime_type, metadata, created_at
FROM artifacts
WHERE ticket_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListArtifactsByTicket(ctx context.Context, ticketID pgtype.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.TicketID,
			&i.AttemptID,
			&i.Type,
			&i.Role,
			&i.Name,
			&i.Url,
			&i.StorageBackend,
			&i.SizeBytes,
			&i.MimeType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
