// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attempts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO attempts (
    workspace_id,
    project_id,
    ticket_id,
    agent_id,
    harness,
    model,
    status,
    lease_expires_at,
    last_heartbeat_at,
    progress_percent,
    current_summary,
    next_step,
    output,
    output_schema,
    failure_reason,
    failure_category,
    blocker,
    trace_id,
    checkpoint_ref,
    completed_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
)
RETURNING id, workspace_id, project_id, ticket_id, agent_id, harness, model, status, lease_expires_at, last_heartbeat_at, progress_percent, current_summary, next_step, output, output_schema, failure_reason, failure_category, blocker, trace_id, checkpoint_ref, started_at, completed_at
`

type CreateAttemptParams struct {
	WorkspaceID     pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	ProjectID       pgtype.UUID        `db:"project_id" json:"project_id"`
	TicketID        pgtype.UUID        `db:"ticket_id" json:"ticket_id"`
	AgentID         string             `db:"agent_id" json:"agent_id"`
	Harness         string             `db:"harness" json:"harness"`
	Model           string             `db:"model" json:"model"`
	Status          string             `db:"status" json:"status"`
	LeaseExpiresAt  pgtype.Timestamptz `db:"lease_expires_at" json:"lease_expires_at"`
	LastHeartbeatAt pgtype.Timestamptz `db:"last_heartbeat_at" json:"last_heartbeat_at"`
	ProgressPercent int32              `db:"progress_percent" json:"progress_percent"`
	CurrentSummary  pgtype.Text        `db:"current_summary" json:"current_summary"`
	NextStep        pgtype.Text        `db:"next_step" json:"next_step"`
	Output          []byte             `db:"output" json:"output"`
	OutputSchema    pgtype.Text        `db:"output_schema" json:"output_schema"`
	FailureReason   pgtype.Text        `db:"failure_reason" json:"failure_reason"`
	FailureCategory pgtype.Text        `db:"failure_category" json:"failure_category"`
	Blocker         []byte             `db:"blocker" json:"blocker"`
	TraceID         pgtype.Text        `db:"trace_id" json:"trace_id"`
	CheckpointRef   pgtype.Text        `db:"checkpoint_ref" json:"checkpoint_ref"`
	CompletedAt     pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, createAttempt,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.TicketID,
		arg.AgentID,
		arg.Harness,
		arg.Model,
		arg.Status,
		arg.LeaseExpiresAt,
		arg.LastHeartbeatAt,
		arg.ProgressPercent,
		arg.CurrentSummary,
		arg.NextStep,
		arg.Output,
		arg.OutputSchema,
		arg.FailureReason,
		arg.FailureCategory,
		arg.Blocker,
		arg.TraceID,
		arg.CheckpointRef,
		arg.CompletedAt,
	)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TicketID,
		&i.AgentID,
		&i.Harness,
		&i.Model,
		&i.Status,
		&i.LeaseExpiresAt,
		&i.LastHeartbeatAt,
		&i.ProgressPercent,
		&i.CurrentSummary,
		&i.NextStep,
		&i.Output,
		&i.OutputSchema,
		&i.FailureReason,
		&i.FailureCategory,
		&i.Blocker,
		&i.TraceID,
		&i.CheckpointRef,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createAttemptCheckpoint = `-- name: CreateAttemptCheckpoint :one
INSERT INTO attempt_checkpoints (
    workspace_id,
    project_id,
    ticket_id,
    attempt_id,
    summary,
    files_touched,
    commands_run,
    next_step,
    risk
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, workspace_id, project_id, ticket_id, attempt_id, summary, files_touched, commands_run, next_step, risk, created_at
`

type CreateAttemptCheckpointParams struct {
	WorkspaceID  pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ProjectID    pgtype.UUID `db:"project_id" json:"project_id"`
	TicketID     pgtype.UUID `db:"ticket_id" json:"ticket_id"`
	AttemptID    pgtype.UUID `db:"attempt_id" json:"attempt_id"`
	Summary      string      `db:"summary" json:"summary"`
	FilesTouched []string    `db:"files_touched" json:"files_touched"`
	CommandsRun  []string    `db:"commands_run" json:"commands_run"`
	NextStep     pgtype.Text `db:"next_step" json:"next_step"`
	Risk         pgtype.Text `db:"risk" json:"risk"`
}

func (q *Queries) CreateAttemptCheckpoint(ctx context.Context, arg CreateAttemptCheckpointParams) (AttemptCheckpoint, error) {
	row := q.db.QueryRow(ctx, createAttemptCheckpoint,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.TicketID,
		arg.AttemptID,
		arg.Summary,
		arg.FilesTouched,
		arg.CommandsRun,
		arg.NextStep,
		arg.Risk,
	)
	var i AttemptCheckpoint
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TicketID,
		&i.AttemptID,
		&i.Summary,
		&i.FilesTouched,
		&i.CommandsRun,
		&i.NextStep,
		&i.Risk,
		&i.CreatedAt,
	)
	return i, err
}

const getAttempt = `-- name: GetAttempt :one
SELECT id, workspace_id, project_id, ticket_id, agent_id, harness, model, status, lease_expires_at, last_heartbeat_at, progress_percent, current_summary, next_step, output, output_schema, failure_reason, failure_category, blocker, trace_id, checkpoint_ref, started_at, completed_at
FROM attempts
WHERE id = $1
`

func (q *Queries) GetAttempt(ctx context.Context, id pgtype.UUID) (Attempt, error) {
	row := q.db.QueryRow(ctx, getAttempt, id)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TicketID,
		&i.AgentID,
		&i.Harness,
		&i.Model,
		&i.Status,
		&i.LeaseExpiresAt,
		&i.LastHeartbeatAt,
		&i.ProgressPercent,
		&i.CurrentSummary,
		&i.NextStep,
		&i.Output,
		&i.OutputSchema,
		&i.FailureReason,
		&i.FailureCategory,
		&i.Blocker,
		&i.TraceID,
		&i.CheckpointRef,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listAttemptCheckpointsByAttempt = `-- name: ListAttemptCheckpointsByAttempt :many
SELECT id, workspace_id, project_id, ticket_id, attempt_id, summary, files_touched, commands_run, next_step, risk, created_at
FROM attempt_checkpoints
WHERE attempt_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAttemptCheckpointsByAttempt(ctx context.Context, attemptID pgtype.UUID) ([]AttemptCheckpoint, error) {
	rows, err := q.db.Query(ctx, listAttemptCheckpointsByAttempt, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttemptCheckpoint{}
	for rows.Next() {
		var i AttemptCheckpoint
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.TicketID,
			&i.AttemptID,
			&i.Summary,
			&i.FilesTouched,
			&i.CommandsRun,
			&i.NextStep,
			&i.Risk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptCheckpointsByTicket = `-- name: ListAttemptCheckpointsByTicket :many
SELECT id, workspace_id, project_id, ticket_id, attempt_id, summary, files_touched, commands_run, next_step, risk, created_at
FROM attempt_checkpoints
WHERE ticket_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAttemptCheckpointsByTicket(ctx context.Context, ticketID pgtype.UUID) ([]AttemptCheckpoint, error) {
	rows, err := q.db.Query(ctx, listAttemptCheckpointsByTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttemptCheckpoint{}
	for rows.Next() {
		var i AttemptCheckpoint
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.TicketID,
			&i.AttemptID,
			&i.Summary,
			&i.FilesTouched,
			&i.CommandsRun,
			&i.NextStep,
			&i.Risk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttemptsByTicket = `-- name: ListAttemptsByTicket :many
SELECT id, workspace_id, project_id, ticket_id, agent_id, harness, model, status, lease_expires_at, last_heartbeat_at, progress_percent, current_summary, next_step, output, output_schema, failure_reason, failure_category, blocker, trace_id, checkpoint_ref, started_at, completed_at
FROM attempts
WHERE ticket_id = $1
ORDER BY started_at DESC
`

func (q *Queries) ListAttemptsByTicket(ctx context.Context, ticketID pgtype.UUID) ([]Attempt, error) {
	rows, err := q.db.Query(ctx, listAttemptsByTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attempt{}
	for rows.Next() {
		var i Attempt
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.TicketID,
			&i.AgentID,
			&i.Harness,
			&i.Model,
			&i.Status,
			&i.LeaseExpiresAt,
			&i.LastHeartbeatAt,
			&i.ProgressPercent,
			&i.CurrentSummary,
			&i.NextStep,
			&i.Output,
			&i.OutputSchema,
			&i.FailureReason,
			&i.FailureCategory,
			&i.Blocker,
			&i.TraceID,
			&i.CheckpointRef,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
