// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: capabilities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAgentCapability = `-- name: GetAgentCapability :one
SELECT id, workspace_id, project_id, agent_id, harness, model, transports, capabilities, tool_names, artifact_roles, preferred_claim, metadata, last_seen_at, created_at, updated_at
FROM agent_capabilities
WHERE workspace_id = $1
  AND project_id = $2
  AND agent_id = $3
  AND harness = $4
`

type GetAgentCapabilityParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ProjectID   pgtype.UUID `db:"project_id" json:"project_id"`
	AgentID     string      `db:"agent_id" json:"agent_id"`
	Harness     string      `db:"harness" json:"harness"`
}

func (q *Queries) GetAgentCapability(ctx context.Context, arg GetAgentCapabilityParams) (AgentCapability, error) {
	row := q.db.QueryRow(ctx, getAgentCapability,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.AgentID,
		arg.Harness,
	)
	var i AgentCapability
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.AgentID,
		&i.Harness,
		&i.Model,
		&i.Transports,
		&i.Capabilities,
		&i.ToolNames,
		&i.ArtifactRoles,
		&i.PreferredClaim,
		&i.Metadata,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentCapabilities = `-- name: ListAgentCapabilities :many
SELECT id, workspace_id, project_id, agent_id, harness, model, transports, capabilities, tool_names, artifact_roles, preferred_claim, metadata, last_seen_at, created_at, updated_at
FROM agent_capabilities
WHERE workspace_id = $1
  AND project_id = $2
  AND ($3::text IS NULL OR harness = $3)
  AND ($4::text IS NULL OR $4 = ANY(capabilities))
ORDER BY harness, agent_id
`

type ListAgentCapabilitiesParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ProjectID   pgtype.UUID `db:"project_id" json:"project_id"`
	Harness     pgtype.Text `db:"harness" json:"harness"`
	Capability  pgtype.Text `db:"capability" json:"capability"`
}

func (q *Queries) ListAgentCapabilities(ctx context.Context, arg ListAgentCapabilitiesParams) ([]AgentCapability, error) {
	rows, err := q.db.Query(ctx, listAgentCapabilities,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Harness,
		arg.Capability,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentCapability{}
	for rows.Next() {
		var i AgentCapability
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.AgentID,
			&i.Harness,
			&i.Model,
			&i.Transports,
			&i.Capabilities,
			&i.ToolNames,
			&i.ArtifactRoles,
			&i.PreferredClaim,
			&i.Metadata,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentCapability = `-- name: UpsertAgentCapability :one
INSERT INTO agent_capabilities (
    workspace_id,
    project_id,
    agent_id,
    harness,
    model,
    transports,
    capabilities,
    tool_names,
    artifact_roles,
    preferred_claim,
    metadata,
    last_seen_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
ON CONFLICT (workspace_id, project_id, agent_id, harness)
DO UPDATE SET
    model = EXCLUDED.model,
    transports = EXCLUDED.transports,
    capabilities = EXCLUDED.capabilities,
    tool_names = EXCLUDED.tool_names,
    artifact_roles = EXCLUDED.artifact_roles,
    preferred_claim = EXCLUDED.preferred_claim,
    metadata = EXCLUDED.metadata,
    last_seen_at = EXCLUDED.last_seen_at,
    updated_at = now()
RETURNING id, workspace_id, project_id, agent_id, harness, model, transports, capabilities, tool_names, artifact_roles, preferred_claim, metadata, last_seen_at, created_at, updated_at
`

type UpsertAgentCapabilityParams struct {
	WorkspaceID    pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	ProjectID      pgtype.UUID        `db:"project_id" json:"project_id"`
	AgentID        string             `db:"agent_id" json:"agent_id"`
	Harness        string             `db:"harness" json:"harness"`
	Model          string             `db:"model" json:"model"`
	Transports     []string           `db:"transports" json:"transports"`
	Capabilities   []string           `db:"capabilities" json:"capabilities"`
	ToolNames      []string           `db:"tool_names" json:"tool_names"`
	ArtifactRoles  []string           `db:"artifact_roles" json:"artifact_roles"`
	PreferredClaim []byte             `db:"preferred_claim" json:"preferred_claim"`
	Metadata       []byte             `db:"metadata" json:"metadata"`
	LastSeenAt     pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
}

func (q *Queries) UpsertAgentCapability(ctx context.Context, arg UpsertAgentCapabilityParams) (AgentCapability, error) {
	row := q.db.QueryRow(ctx, upsertAgentCapability,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.AgentID,
		arg.Harness,
		arg.Model,
		arg.Transports,
		arg.Capabilities,
		arg.ToolNames,
		arg.ArtifactRoles,
		arg.PreferredClaim,
		arg.Metadata,
		arg.LastSeenAt,
	)
	var i AgentCapability
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.AgentID,
		&i.Harness,
		&i.Model,
		&i.Transports,
		&i.Capabilities,
		&i.ToolNames,
		&i.ArtifactRoles,
		&i.PreferredClaim,
		&i.Metadata,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
