// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: claims.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextTicket = `-- name: ClaimNextTicket :one
WITH candidate AS (
    SELECT t.id
    FROM tickets t
    WHERE t.workspace_id = $1
      AND t.project_id = $2
      AND t.status = 'todo'
      AND ($3::text IS NULL OR t.type = $3::text)
      AND (COALESCE(cardinality($4::text[]), 0) = 0 OR t.tags && $4::text[])
      AND (
          COALESCE(cardinality(t.allowed_harnesses), 0) = 0
          OR $5::text = ANY(t.allowed_harnesses)
      )
      AND (
          COALESCE(cardinality(t.required_capabilities), 0) = 0
          OR t.required_capabilities <@ $6::text[]
      )
      AND NOT EXISTS (
          SELECT 1
          FROM ticket_dependencies d
          JOIN tickets dep ON dep.id = d.depends_on_ticket_id
          WHERE d.ticket_id = t.id
            AND dep.status != 'done'
      )
      AND (
          SELECT count(*)::integer
          FROM attempts a
          WHERE a.ticket_id = t.id
            AND a.status IN ('failed', 'expired')
      ) < COALESCE((t.retry_policy->>'max_attempts')::integer, 3)
    ORDER BY t.priority DESC, t.created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
),
updated_ticket AS (
    UPDATE tickets t
    SET status = 'in_progress',
        updated_at = now()
    FROM candidate c
    WHERE t.id = c.id
    RETURNING t.id, t.workspace_id, t.project_id
),
created_attempt AS (
    INSERT INTO attempts (
        workspace_id,
        project_id,
        ticket_id,
        agent_id,
        harness,
        model,
        status,
        lease_expires_at,
        last_heartbeat_at,
        progress_percent,
        output
    )
    SELECT
        t.workspace_id,
        t.project_id,
        t.id,
        $7::text,
        $5::text,
        $8::text,
        'running',
        $9::timestamptz,
        $10::timestamptz,
        0,
        '{}'::jsonb
    FROM updated_ticket t
    RETURNING id, ticket_id
),
claimed_event AS (
    INSERT INTO ticket_events (
        workspace_id,
        project_id,
        ticket_id,
        attempt_id,
        type,
        actor_type,
        actor_id,
        data
    )
    SELECT
        t.workspace_id,
        t.project_id,
        t.id,
        a.id,
        'claimed',
        'agent',
        $7::text,
        jsonb_build_object(
            'attempt_id', a.id,
            'agent_id', $7::text,
            'harness', $5::text,
            'model', $8::text
        )
    FROM updated_ticket t
    JOIN created_attempt a ON a.ticket_id = t.id
    RETURNING id
)
SELECT
    t.id AS ticket_id,
    a.id AS attempt_id
FROM updated_ticket t
JOIN created_attempt a ON a.ticket_id = t.id
`

type ClaimNextTicketParams struct {
	WorkspaceID     pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	ProjectID       pgtype.UUID        `db:"project_id" json:"project_id"`
	TicketType      pgtype.Text        `db:"ticket_type" json:"ticket_type"`
	Tags            []string           `db:"tags" json:"tags"`
	Harness         string             `db:"harness" json:"harness"`
	Capabilities    []string           `db:"capabilities" json:"capabilities"`
	AgentID         string             `db:"agent_id" json:"agent_id"`
	Model           string             `db:"model" json:"model"`
	LeaseExpiresAt  pgtype.Timestamptz `db:"lease_expires_at" json:"lease_expires_at"`
	LastHeartbeatAt pgtype.Timestamptz `db:"last_heartbeat_at" json:"last_heartbeat_at"`
}

type ClaimNextTicketRow struct {
	TicketID  pgtype.UUID `db:"ticket_id" json:"ticket_id"`
	AttemptID pgtype.UUID `db:"attempt_id" json:"attempt_id"`
}

func (q *Queries) ClaimNextTicket(ctx context.Context, arg ClaimNextTicketParams) (ClaimNextTicketRow, error) {
	row := q.db.QueryRow(ctx, claimNextTicket,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.TicketType,
		arg.Tags,
		arg.Harness,
		arg.Capabilities,
		arg.AgentID,
		arg.Model,
		arg.LeaseExpiresAt,
		arg.LastHeartbeatAt,
	)
	var i ClaimNextTicketRow
	err := row.Scan(&i.TicketID, &i.AttemptID)
	return i, err
}
