// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicketEvent = `-- name: CreateTicketEvent :one
INSERT INTO ticket_events (
    workspace_id,
    project_id,
    ticket_id,
    attempt_id,
    type,
    actor_type,
    actor_id,
    data
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, workspace_id, project_id, ticket_id, attempt_id, type, actor_type, actor_id, data, created_at
`

type CreateTicketEventParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ProjectID   pgtype.UUID `db:"project_id" json:"project_id"`
	TicketID    pgtype.UUID `db:"ticket_id" json:"ticket_id"`
	AttemptID   pgtype.UUID `db:"attempt_id" json:"attempt_id"`
	Type        string      `db:"type" json:"type"`
	ActorType   string      `db:"actor_type" json:"actor_type"`
	ActorID     pgtype.Text `db:"actor_id" json:"actor_id"`
	Data        []byte      `db:"data" json:"data"`
}

func (q *Queries) CreateTicketEvent(ctx context.Context, arg CreateTicketEventParams) (TicketEvent, error) {
	row := q.db.QueryRow(ctx, createTicketEvent,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.TicketID,
		arg.AttemptID,
		arg.Type,
		arg.ActorType,
		arg.ActorID,
		arg.Data,
	)
	var i TicketEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TicketID,
		&i.AttemptID,
		&i.Type,
		&i.ActorType,
		&i.ActorID,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const listTicketEventsByTicket = `-- name: ListTicketEventsByTicket :many
SELECT id, workspace_id, project_id, ticket_id, attempt_id, type, actor_type, actor_id, data, created_at
FROM ticket_events
WHERE ticket_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListTicketEventsByTicket(ctx context.Context, ticketID pgtype.UUID) ([]TicketEvent, error) {
	rows, err := q.db.Query(ctx, listTicketEventsByTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketEvent{}
	for rows.Next() {
		var i TicketEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.TicketID,
			&i.AttemptID,
			&i.Type,
			&i.ActorType,
			&i.ActorID,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
