// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (
    workspace_id,
    actor_id,
    key,
    route,
    request_hash,
    response_body,
    expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, actor_id, key, route, request_hash, response_body, created_at, expires_at
`

type CreateIdempotencyKeyParams struct {
	WorkspaceID  pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	ActorID      string             `db:"actor_id" json:"actor_id"`
	Key          string             `db:"key" json:"key"`
	Route        string             `db:"route" json:"route"`
	RequestHash  string             `db:"request_hash" json:"request_hash"`
	ResponseBody []byte             `db:"response_body" json:"response_body"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.WorkspaceID,
		arg.ActorID,
		arg.Key,
		arg.Route,
		arg.RequestHash,
		arg.ResponseBody,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ActorID,
		&i.Key,
		&i.Route,
		&i.RequestHash,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, workspace_id, actor_id, key, route, request_hash, response_body, created_at, expires_at
FROM idempotency_keys
WHERE workspace_id = $1
  AND actor_id = $2
  AND route = $3
  AND key = $4
`

type GetIdempotencyKeyParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ActorID     string      `db:"actor_id" json:"actor_id"`
	Route       string      `db:"route" json:"route"`
	Key         string      `db:"key" json:"key"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey,
		arg.WorkspaceID,
		arg.ActorID,
		arg.Route,
		arg.Key,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ActorID,
		&i.Key,
		&i.Route,
		&i.RequestHash,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
