// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttemptMetrics = `-- name: CreateAttemptMetrics :one
INSERT INTO attempt_metrics (
    attempt_id,
    workspace_id,
    project_id,
    tokens_in,
    tokens_out,
    cost_usd,
    duration_seconds,
    retry_count,
    agent_success_score,
    human_rating
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, attempt_id, workspace_id, project_id, tokens_in, tokens_out, cost_usd, duration_seconds, retry_count, agent_success_score, human_rating, created_at
`

type CreateAttemptMetricsParams struct {
	AttemptID         pgtype.UUID    `db:"attempt_id" json:"attempt_id"`
	WorkspaceID       pgtype.UUID    `db:"workspace_id" json:"workspace_id"`
	ProjectID         pgtype.UUID    `db:"project_id" json:"project_id"`
	TokensIn          int64          `db:"tokens_in" json:"tokens_in"`
	TokensOut         int64          `db:"tokens_out" json:"tokens_out"`
	CostUsd           pgtype.Numeric `db:"cost_usd" json:"cost_usd"`
	DurationSeconds   pgtype.Numeric `db:"duration_seconds" json:"duration_seconds"`
	RetryCount        int32          `db:"retry_count" json:"retry_count"`
	AgentSuccessScore pgtype.Numeric `db:"agent_success_score" json:"agent_success_score"`
	HumanRating       pgtype.Int4    `db:"human_rating" json:"human_rating"`
}

func (q *Queries) CreateAttemptMetrics(ctx context.Context, arg CreateAttemptMetricsParams) (AttemptMetric, error) {
	row := q.db.QueryRow(ctx, createAttemptMetrics,
		arg.AttemptID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.TokensIn,
		arg.TokensOut,
		arg.CostUsd,
		arg.DurationSeconds,
		arg.RetryCount,
		arg.AgentSuccessScore,
		arg.HumanRating,
	)
	var i AttemptMetric
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TokensIn,
		&i.TokensOut,
		&i.CostUsd,
		&i.DurationSeconds,
		&i.RetryCount,
		&i.AgentSuccessScore,
		&i.HumanRating,
		&i.CreatedAt,
	)
	return i, err
}

const getAttemptMetrics = `-- name: GetAttemptMetrics :one
SELECT id, attempt_id, workspace_id, project_id, tokens_in, tokens_out, cost_usd, duration_seconds, retry_count, agent_success_score, human_rating, created_at
FROM attempt_metrics
WHERE attempt_id = $1
`

func (q *Queries) GetAttemptMetrics(ctx context.Context, attemptID pgtype.UUID) (AttemptMetric, error) {
	row := q.db.QueryRow(ctx, getAttemptMetrics, attemptID)
	var i AttemptMetric
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TokensIn,
		&i.TokensOut,
		&i.CostUsd,
		&i.DurationSeconds,
		&i.RetryCount,
		&i.AgentSuccessScore,
		&i.HumanRating,
		&i.CreatedAt,
	)
	return i, err
}
