// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentCapability struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID    pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	ProjectID      pgtype.UUID        `db:"project_id" json:"project_id"`
	AgentID        string             `db:"agent_id" json:"agent_id"`
	Harness        string             `db:"harness" json:"harness"`
	Model          string             `db:"model" json:"model"`
	Transports     []string           `db:"transports" json:"transports"`
	Capabilities   []string           `db:"capabilities" json:"capabilities"`
	ToolNames      []string           `db:"tool_names" json:"tool_names"`
	ArtifactRoles  []string           `db:"artifact_roles" json:"artifact_roles"`
	PreferredClaim []byte             `db:"preferred_claim" json:"preferred_claim"`
	Metadata       []byte             `db:"metadata" json:"metadata"`
	LastSeenAt     pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ApiKey struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	Name        string             `db:"name" json:"name"`
	KeyHash     string             `db:"key_hash" json:"key_hash"`
	ActorType   string             `db:"actor_type" json:"actor_type"`
	ActorID     string             `db:"actor_id" json:"actor_id"`
	Scopes      []string           `db:"scopes" json:"scopes"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastUsedAt  pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	RevokedAt   pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

type Artifact struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID    pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	ProjectID      pgtype.UUID        `db:"project_id" json:"project_id"`
	TicketID       pgtype.UUID        `db:"ticket_id" json:"ticket_id"`
	AttemptID      pgtype.UUID        `db:"attempt_id" json:"attempt_id"`
	Type           string             `db:"type" json:"type"`
	Role           string             `db:"role" json:"role"`
	Name           string             `db:"name" json:"name"`
	Url            string             `db:"url" json:"url"`
	StorageBackend string             `db:"storage_backend" json:"storage_backend"`
	SizeBytes      int64              `db:"size_bytes" json:"size_bytes"`
	MimeType       string             `db:"mime_type" json:"mime_type"`
	Metadata       []byte             `db:"metadata" json:"metadata"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Attempt struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID     pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	ProjectID       pgtype.UUID        `db:"project_id" json:"project_id"`
	TicketID        pgtype.UUID        `db:"ticket_id" json:"ticket_id"`
	AgentID         string             `db:"agent_id" json:"agent_id"`
	Harness         string             `db:"harness" json:"harness"`
	Model           string             `db:"model" json:"model"`
	Status          string             `db:"status" json:"status"`
	LeaseExpiresAt  pgtype.Timestamptz `db:"lease_expires_at" json:"lease_expires_at"`
	LastHeartbeatAt pgtype.Timestamptz `db:"last_heartbeat_at" json:"last_heartbeat_at"`
	ProgressPercent int32              `db:"progress_percent" json:"progress_percent"`
	CurrentSummary  pgtype.Text        `db:"current_summary" json:"current_summary"`
	NextStep        pgtype.Text        `db:"next_step" json:"next_step"`
	Output          []byte             `db:"output" json:"output"`
	OutputSchema    pgtype.Text        `db:"output_schema" json:"output_schema"`
	FailureReason   pgtype.Text        `db:"failure_reason" json:"failure_reason"`
	FailureCategory pgtype.Text        `db:"failure_category" json:"failure_category"`
	Blocker         []byte             `db:"blocker" json:"blocker"`
	TraceID         pgtype.Text        `db:"trace_id" json:"trace_id"`
	CheckpointRef   pgtype.Text        `db:"checkpoint_ref" json:"checkpoint_ref"`
	StartedAt       pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt     pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

type AttemptCheckpoint struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID  pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	ProjectID    pgtype.UUID        `db:"project_id" json:"project_id"`
	TicketID     pgtype.UUID        `db:"ticket_id" json:"ticket_id"`
	AttemptID    pgtype.UUID        `db:"attempt_id" json:"attempt_id"`
	Summary      string             `db:"summary" json:"summary"`
	FilesTouched []string           `db:"files_touched" json:"files_touched"`
	CommandsRun  []string           `db:"commands_run" json:"commands_run"`
	NextStep     pgtype.Text        `db:"next_step" json:"next_step"`
	Risk         pgtype.Text        `db:"risk" json:"risk"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AttemptMetric struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	AttemptID         pgtype.UUID        `db:"attempt_id" json:"attempt_id"`
	WorkspaceID       pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	ProjectID         pgtype.UUID        `db:"project_id" json:"project_id"`
	TokensIn          int64              `db:"tokens_in" json:"tokens_in"`
	TokensOut         int64              `db:"tokens_out" json:"tokens_out"`
	CostUsd           pgtype.Numeric     `db:"cost_usd" json:"cost_usd"`
	DurationSeconds   pgtype.Numeric     `db:"duration_seconds" json:"duration_seconds"`
	RetryCount        int32              `db:"retry_count" json:"retry_count"`
	AgentSuccessScore pgtype.Numeric     `db:"agent_success_score" json:"agent_success_score"`
	HumanRating       pgtype.Int4        `db:"human_rating" json:"human_rating"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type IdempotencyKey struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID  pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	ActorID      string             `db:"actor_id" json:"actor_id"`
	Key          string             `db:"key" json:"key"`
	Route        string             `db:"route" json:"route"`
	RequestHash  string             `db:"request_hash" json:"request_hash"`
	ResponseBody []byte             `db:"response_body" json:"response_body"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type Project struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	Name        string             `db:"name" json:"name"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Ticket struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID          pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	ProjectID            pgtype.UUID        `db:"project_id" json:"project_id"`
	ParentID             pgtype.UUID        `db:"parent_id" json:"parent_id"`
	RootID               pgtype.UUID        `db:"root_id" json:"root_id"`
	SourceAttemptID      pgtype.UUID        `db:"source_attempt_id" json:"source_attempt_id"`
	SourceArtifactID     pgtype.UUID        `db:"source_artifact_id" json:"source_artifact_id"`
	Title                string             `db:"title" json:"title"`
	Description          string             `db:"description" json:"description"`
	Type                 string             `db:"type" json:"type"`
	Status               string             `db:"status" json:"status"`
	Priority             int32              `db:"priority" json:"priority"`
	Tags                 []string           `db:"tags" json:"tags"`
	AcceptanceCriteria   []string           `db:"acceptance_criteria" json:"acceptance_criteria"`
	VerificationCommands []byte             `db:"verification_commands" json:"verification_commands"`
	ExpectedArtifacts    []string           `db:"expected_artifacts" json:"expected_artifacts"`
	RelevantPaths        []string           `db:"relevant_paths" json:"relevant_paths"`
	RequiredTools        []string           `db:"required_tools" json:"required_tools"`
	RequiredPermissions  []string           `db:"required_permissions" json:"required_permissions"`
	Environment          []byte             `db:"environment" json:"environment"`
	Input                []byte             `db:"input" json:"input"`
	InputSchema          pgtype.Text        `db:"input_schema" json:"input_schema"`
	RequiredCapabilities []string           `db:"required_capabilities" json:"required_capabilities"`
	AllowedHarnesses     []string           `db:"allowed_harnesses" json:"allowed_harnesses"`
	RetryPolicy          []byte             `db:"retry_policy" json:"retry_policy"`
	CreatedBy            string             `db:"created_by" json:"created_by"`
	CreatedByID          pgtype.Text        `db:"created_by_id" json:"created_by_id"`
	CreationReason       pgtype.Text        `db:"creation_reason" json:"creation_reason"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TicketDependency struct {
	TicketID          pgtype.UUID        `db:"ticket_id" json:"ticket_id"`
	DependsOnTicketID pgtype.UUID        `db:"depends_on_ticket_id" json:"depends_on_ticket_id"`
	WorkspaceID       pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	ProjectID         pgtype.UUID        `db:"project_id" json:"project_id"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type TicketEvent struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID   pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	ProjectID     pgtype.UUID        `db:"project_id" json:"project_id"`
	TicketID      pgtype.UUID        `db:"ticket_id" json:"ticket_id"`
	AttemptID     pgtype.UUID        `db:"attempt_id" json:"attempt_id"`
	Type          string             `db:"type" json:"type"`
	ActorType     string             `db:"actor_type" json:"actor_type"`
	ActorID       pgtype.Text        `db:"actor_id" json:"actor_id"`
	Data          []byte             `db:"data" json:"data"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	EventSequence int64              `db:"event_sequence" json:"event_sequence"`
}

type WebhookDelivery struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	SubscriptionID pgtype.UUID        `db:"subscription_id" json:"subscription_id"`
	EventID        pgtype.UUID        `db:"event_id" json:"event_id"`
	WorkspaceID    pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	ProjectID      pgtype.UUID        `db:"project_id" json:"project_id"`
	TicketID       pgtype.UUID        `db:"ticket_id" json:"ticket_id"`
	AttemptID      pgtype.UUID        `db:"attempt_id" json:"attempt_id"`
	Status         string             `db:"status" json:"status"`
	Payload        []byte             `db:"payload" json:"payload"`
	AttemptCount   int32              `db:"attempt_count" json:"attempt_count"`
	MaxAttempts    int32              `db:"max_attempts" json:"max_attempts"`
	NextAttemptAt  pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	LockedUntil    pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
	LastAttemptAt  pgtype.Timestamptz `db:"last_attempt_at" json:"last_attempt_at"`
	DeliveredAt    pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	ResponseStatus pgtype.Int4        `db:"response_status" json:"response_status"`
	ResponseBody   pgtype.Text        `db:"response_body" json:"response_body"`
	Error          pgtype.Text        `db:"error" json:"error"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ClaimToken     pgtype.UUID        `db:"claim_token" json:"claim_token"`
}

type WebhookSubscription struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	ProjectID   pgtype.UUID        `db:"project_id" json:"project_id"`
	EndpointUrl string             `db:"endpoint_url" json:"endpoint_url"`
	Secret      pgtype.Text        `db:"secret" json:"secret"`
	EventTypes  []string           `db:"event_types" json:"event_types"`
	Active      bool               `db:"active" json:"active"`
	MaxAttempts int32              `db:"max_attempts" json:"max_attempts"`
	Description string             `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Workspace struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type WorkspaceMember struct {
	WorkspaceID pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	ActorType   string             `db:"actor_type" json:"actor_type"`
	ActorID     string             `db:"actor_id" json:"actor_id"`
	Role        string             `db:"role" json:"role"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
