// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (
    workspace_id,
    project_id,
    parent_id,
    root_id,
    source_attempt_id,
    source_artifact_id,
    title,
    description,
    type,
    status,
    priority,
    tags,
    acceptance_criteria,
    verification_commands,
    expected_artifacts,
    relevant_paths,
    required_tools,
    required_permissions,
    environment,
    input,
    input_schema,
    required_capabilities,
    allowed_harnesses,
    retry_policy,
    created_by,
    created_by_id,
    creation_reason
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27
)
RETURNING id, workspace_id, project_id, parent_id, root_id, source_attempt_id, source_artifact_id, title, description, type, status, priority, tags, acceptance_criteria, verification_commands, expected_artifacts, relevant_paths, required_tools, required_permissions, environment, input, input_schema, required_capabilities, allowed_harnesses, retry_policy, created_by, created_by_id, creation_reason, created_at, updated_at
`

type CreateTicketParams struct {
	WorkspaceID          pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ProjectID            pgtype.UUID `db:"project_id" json:"project_id"`
	ParentID             pgtype.UUID `db:"parent_id" json:"parent_id"`
	RootID               pgtype.UUID `db:"root_id" json:"root_id"`
	SourceAttemptID      pgtype.UUID `db:"source_attempt_id" json:"source_attempt_id"`
	SourceArtifactID     pgtype.UUID `db:"source_artifact_id" json:"source_artifact_id"`
	Title                string      `db:"title" json:"title"`
	Description          string      `db:"description" json:"description"`
	Type                 string      `db:"type" json:"type"`
	Status               string      `db:"status" json:"status"`
	Priority             int32       `db:"priority" json:"priority"`
	Tags                 []string    `db:"tags" json:"tags"`
	AcceptanceCriteria   []string    `db:"acceptance_criteria" json:"acceptance_criteria"`
	VerificationCommands []byte      `db:"verification_commands" json:"verification_commands"`
	ExpectedArtifacts    []string    `db:"expected_artifacts" json:"expected_artifacts"`
	RelevantPaths        []string    `db:"relevant_paths" json:"relevant_paths"`
	RequiredTools        []string    `db:"required_tools" json:"required_tools"`
	RequiredPermissions  []string    `db:"required_permissions" json:"required_permissions"`
	Environment          []byte      `db:"environment" json:"environment"`
	Input                []byte      `db:"input" json:"input"`
	InputSchema          pgtype.Text `db:"input_schema" json:"input_schema"`
	RequiredCapabilities []string    `db:"required_capabilities" json:"required_capabilities"`
	AllowedHarnesses     []string    `db:"allowed_harnesses" json:"allowed_harnesses"`
	RetryPolicy          []byte      `db:"retry_policy" json:"retry_policy"`
	CreatedBy            string      `db:"created_by" json:"created_by"`
	CreatedByID          pgtype.Text `db:"created_by_id" json:"created_by_id"`
	CreationReason       pgtype.Text `db:"creation_reason" json:"creation_reason"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.ParentID,
		arg.RootID,
		arg.SourceAttemptID,
		arg.SourceArtifactID,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Status,
		arg.Priority,
		arg.Tags,
		arg.AcceptanceCriteria,
		arg.VerificationCommands,
		arg.ExpectedArtifacts,
		arg.RelevantPaths,
		arg.RequiredTools,
		arg.RequiredPermissions,
		arg.Environment,
		arg.Input,
		arg.InputSchema,
		arg.RequiredCapabilities,
		arg.AllowedHarnesses,
		arg.RetryPolicy,
		arg.CreatedBy,
		arg.CreatedByID,
		arg.CreationReason,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.ParentID,
		&i.RootID,
		&i.SourceAttemptID,
		&i.SourceArtifactID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.Tags,
		&i.AcceptanceCriteria,
		&i.VerificationCommands,
		&i.ExpectedArtifacts,
		&i.RelevantPaths,
		&i.RequiredTools,
		&i.RequiredPermissions,
		&i.Environment,
		&i.Input,
		&i.InputSchema,
		&i.RequiredCapabilities,
		&i.AllowedHarnesses,
		&i.RetryPolicy,
		&i.CreatedBy,
		&i.CreatedByID,
		&i.CreationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTicketDependency = `-- name: CreateTicketDependency :one
INSERT INTO ticket_dependencies (
    ticket_id,
    depends_on_ticket_id,
    workspace_id,
    project_id
)
VALUES ($1, $2, $3, $4)
RETURNING ticket_id, depends_on_ticket_id, workspace_id, project_id, created_at
`

type CreateTicketDependencyParams struct {
	TicketID          pgtype.UUID `db:"ticket_id" json:"ticket_id"`
	DependsOnTicketID pgtype.UUID `db:"depends_on_ticket_id" json:"depends_on_ticket_id"`
	WorkspaceID       pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ProjectID         pgtype.UUID `db:"project_id" json:"project_id"`
}

func (q *Queries) CreateTicketDependency(ctx context.Context, arg CreateTicketDependencyParams) (TicketDependency, error) {
	row := q.db.QueryRow(ctx, createTicketDependency,
		arg.TicketID,
		arg.DependsOnTicketID,
		arg.WorkspaceID,
		arg.ProjectID,
	)
	var i TicketDependency
	err := row.Scan(
		&i.TicketID,
		&i.DependsOnTicketID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.CreatedAt,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT id, workspace_id, project_id, parent_id, root_id, source_attempt_id, source_artifact_id, title, description, type, status, priority, tags, acceptance_criteria, verification_commands, expected_artifacts, relevant_paths, required_tools, required_permissions, environment, input, input_schema, required_capabilities, allowed_harnesses, retry_policy, created_by, created_by_id, creation_reason, created_at, updated_at
FROM tickets
WHERE id = $1
`

func (q *Queries) GetTicket(ctx context.Context, id pgtype.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.ParentID,
		&i.RootID,
		&i.SourceAttemptID,
		&i.SourceArtifactID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.Tags,
		&i.AcceptanceCriteria,
		&i.VerificationCommands,
		&i.ExpectedArtifacts,
		&i.RelevantPaths,
		&i.RequiredTools,
		&i.RequiredPermissions,
		&i.Environment,
		&i.Input,
		&i.InputSchema,
		&i.RequiredCapabilities,
		&i.AllowedHarnesses,
		&i.RetryPolicy,
		&i.CreatedBy,
		&i.CreatedByID,
		&i.CreationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTicketDependencies = `-- name: ListTicketDependencies :many
SELECT ticket_id, depends_on_ticket_id, workspace_id, project_id, created_at
FROM ticket_dependencies
WHERE ticket_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListTicketDependencies(ctx context.Context, ticketID pgtype.UUID) ([]TicketDependency, error) {
	rows, err := q.db.Query(ctx, listTicketDependencies, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketDependency{}
	for rows.Next() {
		var i TicketDependency
		if err := rows.Scan(
			&i.TicketID,
			&i.DependsOnTicketID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTickets = `-- name: ListTickets :many
SELECT id, workspace_id, project_id, parent_id, root_id, source_attempt_id, source_artifact_id, title, description, type, status, priority, tags, acceptance_criteria, verification_commands, expected_artifacts, relevant_paths, required_tools, required_permissions, environment, input, input_schema, required_capabilities, allowed_harnesses, retry_policy, created_by, created_by_id, creation_reason, created_at, updated_at
FROM tickets
WHERE workspace_id = $1
  AND project_id = $2
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::text IS NULL OR type = $4::text)
ORDER BY priority ASC, created_at ASC
LIMIT $6::integer
OFFSET $5::integer
`

type ListTicketsParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ProjectID   pgtype.UUID `db:"project_id" json:"project_id"`
	Status      pgtype.Text `db:"status" json:"status"`
	Type        pgtype.Text `db:"type" json:"type"`
	Offset      int32       `db:"offset" json:"offset"`
	Limit       int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTickets,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Status,
		arg.Type,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.ParentID,
			&i.RootID,
			&i.SourceAttemptID,
			&i.SourceArtifactID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.Priority,
			&i.Tags,
			&i.AcceptanceCriteria,
			&i.VerificationCommands,
			&i.ExpectedArtifacts,
			&i.RelevantPaths,
			&i.RequiredTools,
			&i.RequiredPermissions,
			&i.Environment,
			&i.Input,
			&i.InputSchema,
			&i.RequiredCapabilities,
			&i.AllowedHarnesses,
			&i.RetryPolicy,
			&i.CreatedBy,
			&i.CreatedByID,
			&i.CreationReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionTicket = `-- name: TransitionTicket :one
WITH updated_ticket AS (
    UPDATE tickets
    SET status = $1::text,
        updated_at = now()
    WHERE id = $2::uuid
      AND status = ANY($3::text[])
    RETURNING id, workspace_id, project_id, parent_id, root_id, source_attempt_id, source_artifact_id, title, description, type, status, priority, tags, acceptance_criteria, verification_commands, expected_artifacts, relevant_paths, required_tools, required_permissions, environment, input, input_schema, required_capabilities, allowed_harnesses, retry_policy, created_by, created_by_id, creation_reason, created_at, updated_at
),
transition_event AS (
    INSERT INTO ticket_events (
        workspace_id,
        project_id,
        ticket_id,
        type,
        actor_type,
        actor_id,
        data
    )
    SELECT
        workspace_id,
        project_id,
        id,
        $4::text,
        $5::text,
        $6::text,
        $7::jsonb
    FROM updated_ticket
    RETURNING id
)
SELECT id, workspace_id, project_id, parent_id, root_id, source_attempt_id, source_artifact_id, title, description, type, status, priority, tags, acceptance_criteria, verification_commands, expected_artifacts, relevant_paths, required_tools, required_permissions, environment, input, input_schema, required_capabilities, allowed_harnesses, retry_policy, created_by, created_by_id, creation_reason, created_at, updated_at
FROM updated_ticket
`

type TransitionTicketParams struct {
	Status          string      `db:"status" json:"status"`
	ID              pgtype.UUID `db:"id" json:"id"`
	AllowedStatuses []string    `db:"allowed_statuses" json:"allowed_statuses"`
	Type            string      `db:"type" json:"type"`
	ActorType       string      `db:"actor_type" json:"actor_type"`
	ActorID         pgtype.Text `db:"actor_id" json:"actor_id"`
	Data            []byte      `db:"data" json:"data"`
}

type TransitionTicketRow struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	WorkspaceID          pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	ProjectID            pgtype.UUID        `db:"project_id" json:"project_id"`
	ParentID             pgtype.UUID        `db:"parent_id" json:"parent_id"`
	RootID               pgtype.UUID        `db:"root_id" json:"root_id"`
	SourceAttemptID      pgtype.UUID        `db:"source_attempt_id" json:"source_attempt_id"`
	SourceArtifactID     pgtype.UUID        `db:"source_artifact_id" json:"source_artifact_id"`
	Title                string             `db:"title" json:"title"`
	Description          string             `db:"description" json:"description"`
	Type                 string             `db:"type" json:"type"`
	Status               string             `db:"status" json:"status"`
	Priority             int32              `db:"priority" json:"priority"`
	Tags                 []string           `db:"tags" json:"tags"`
	AcceptanceCriteria   []string           `db:"acceptance_criteria" json:"acceptance_criteria"`
	VerificationCommands []byte             `db:"verification_commands" json:"verification_commands"`
	ExpectedArtifacts    []string           `db:"expected_artifacts" json:"expected_artifacts"`
	RelevantPaths        []string           `db:"relevant_paths" json:"relevant_paths"`
	RequiredTools        []string           `db:"required_tools" json:"required_tools"`
	RequiredPermissions  []string           `db:"required_permissions" json:"required_permissions"`
	Environment          []byte             `db:"environment" json:"environment"`
	Input                []byte             `db:"input" json:"input"`
	InputSchema          pgtype.Text        `db:"input_schema" json:"input_schema"`
	RequiredCapabilities []string           `db:"required_capabilities" json:"required_capabilities"`
	AllowedHarnesses     []string           `db:"allowed_harnesses" json:"allowed_harnesses"`
	RetryPolicy          []byte             `db:"retry_policy" json:"retry_policy"`
	CreatedBy            string             `db:"created_by" json:"created_by"`
	CreatedByID          pgtype.Text        `db:"created_by_id" json:"created_by_id"`
	CreationReason       pgtype.Text        `db:"creation_reason" json:"creation_reason"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) TransitionTicket(ctx context.Context, arg TransitionTicketParams) (TransitionTicketRow, error) {
	row := q.db.QueryRow(ctx, transitionTicket,
		arg.Status,
		arg.ID,
		arg.AllowedStatuses,
		arg.Type,
		arg.ActorType,
		arg.ActorID,
		arg.Data,
	)
	var i TransitionTicketRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.ParentID,
		&i.RootID,
		&i.SourceAttemptID,
		&i.SourceArtifactID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.Tags,
		&i.AcceptanceCriteria,
		&i.VerificationCommands,
		&i.ExpectedArtifacts,
		&i.RelevantPaths,
		&i.RequiredTools,
		&i.RequiredPermissions,
		&i.Environment,
		&i.Input,
		&i.InputSchema,
		&i.RequiredCapabilities,
		&i.AllowedHarnesses,
		&i.RetryPolicy,
		&i.CreatedBy,
		&i.CreatedByID,
		&i.CreationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTicket = `-- name: UpdateTicket :one
UPDATE tickets
SET title = COALESCE($1::text, title),
    description = COALESCE($2::text, description),
    tags = CASE
        WHEN $3::boolean THEN $4::text[]
        ELSE tags
    END,
    acceptance_criteria = CASE
        WHEN $5::boolean THEN $6::text[]
        ELSE acceptance_criteria
    END,
    verification_commands = CASE
        WHEN $7::boolean THEN $8::jsonb
        ELSE verification_commands
    END,
    relevant_paths = CASE
        WHEN $9::boolean THEN $10::text[]
        ELSE relevant_paths
    END,
    updated_at = now()
WHERE id = $11
RETURNING id, workspace_id, project_id, parent_id, root_id, source_attempt_id, source_artifact_id, title, description, type, status, priority, tags, acceptance_criteria, verification_commands, expected_artifacts, relevant_paths, required_tools, required_permissions, environment, input, input_schema, required_capabilities, allowed_harnesses, retry_policy, created_by, created_by_id, creation_reason, created_at, updated_at
`

type UpdateTicketParams struct {
	Title                      pgtype.Text `db:"title" json:"title"`
	Description                pgtype.Text `db:"description" json:"description"`
	UpdateTags                 bool        `db:"update_tags" json:"update_tags"`
	Tags                       []string    `db:"tags" json:"tags"`
	UpdateAcceptanceCriteria   bool        `db:"update_acceptance_criteria" json:"update_acceptance_criteria"`
	AcceptanceCriteria         []string    `db:"acceptance_criteria" json:"acceptance_criteria"`
	UpdateVerificationCommands bool        `db:"update_verification_commands" json:"update_verification_commands"`
	VerificationCommands       []byte      `db:"verification_commands" json:"verification_commands"`
	UpdateRelevantPaths        bool        `db:"update_relevant_paths" json:"update_relevant_paths"`
	RelevantPaths              []string    `db:"relevant_paths" json:"relevant_paths"`
	ID                         pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicket,
		arg.Title,
		arg.Description,
		arg.UpdateTags,
		arg.Tags,
		arg.UpdateAcceptanceCriteria,
		arg.AcceptanceCriteria,
		arg.UpdateVerificationCommands,
		arg.VerificationCommands,
		arg.UpdateRelevantPaths,
		arg.RelevantPaths,
		arg.ID,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.ParentID,
		&i.RootID,
		&i.SourceAttemptID,
		&i.SourceArtifactID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.Tags,
		&i.AcceptanceCriteria,
		&i.VerificationCommands,
		&i.ExpectedArtifacts,
		&i.RelevantPaths,
		&i.RequiredTools,
		&i.RequiredPermissions,
		&i.Environment,
		&i.Input,
		&i.InputSchema,
		&i.RequiredCapabilities,
		&i.AllowedHarnesses,
		&i.RetryPolicy,
		&i.CreatedBy,
		&i.CreatedByID,
		&i.CreationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
