// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (
    workspace_id,
    project_id,
    parent_id,
    root_id,
    source_attempt_id,
    source_artifact_id,
    title,
    description,
    type,
    status,
    priority,
    tags,
    acceptance_criteria,
    verification_commands,
    expected_artifacts,
    relevant_paths,
    required_tools,
    required_permissions,
    environment,
    input,
    input_schema,
    required_capabilities,
    allowed_harnesses,
    retry_policy,
    created_by,
    created_by_id,
    creation_reason
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27
)
RETURNING id, workspace_id, project_id, parent_id, root_id, source_attempt_id, source_artifact_id, title, description, type, status, priority, tags, acceptance_criteria, verification_commands, expected_artifacts, relevant_paths, required_tools, required_permissions, environment, input, input_schema, required_capabilities, allowed_harnesses, retry_policy, created_by, created_by_id, creation_reason, created_at, updated_at
`

type CreateTicketParams struct {
	WorkspaceID          pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ProjectID            pgtype.UUID `db:"project_id" json:"project_id"`
	ParentID             pgtype.UUID `db:"parent_id" json:"parent_id"`
	RootID               pgtype.UUID `db:"root_id" json:"root_id"`
	SourceAttemptID      pgtype.UUID `db:"source_attempt_id" json:"source_attempt_id"`
	SourceArtifactID     pgtype.UUID `db:"source_artifact_id" json:"source_artifact_id"`
	Title                string      `db:"title" json:"title"`
	Description          string      `db:"description" json:"description"`
	Type                 string      `db:"type" json:"type"`
	Status               string      `db:"status" json:"status"`
	Priority             int32       `db:"priority" json:"priority"`
	Tags                 []string    `db:"tags" json:"tags"`
	AcceptanceCriteria   []string    `db:"acceptance_criteria" json:"acceptance_criteria"`
	VerificationCommands []byte      `db:"verification_commands" json:"verification_commands"`
	ExpectedArtifacts    []string    `db:"expected_artifacts" json:"expected_artifacts"`
	RelevantPaths        []string    `db:"relevant_paths" json:"relevant_paths"`
	RequiredTools        []string    `db:"required_tools" json:"required_tools"`
	RequiredPermissions  []string    `db:"required_permissions" json:"required_permissions"`
	Environment          []byte      `db:"environment" json:"environment"`
	Input                []byte      `db:"input" json:"input"`
	InputSchema          pgtype.Text `db:"input_schema" json:"input_schema"`
	RequiredCapabilities []string    `db:"required_capabilities" json:"required_capabilities"`
	AllowedHarnesses     []string    `db:"allowed_harnesses" json:"allowed_harnesses"`
	RetryPolicy          []byte      `db:"retry_policy" json:"retry_policy"`
	CreatedBy            string      `db:"created_by" json:"created_by"`
	CreatedByID          pgtype.Text `db:"created_by_id" json:"created_by_id"`
	CreationReason       pgtype.Text `db:"creation_reason" json:"creation_reason"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.ParentID,
		arg.RootID,
		arg.SourceAttemptID,
		arg.SourceArtifactID,
		arg.Title,
		arg.Description,
		arg.Type,
		arg.Status,
		arg.Priority,
		arg.Tags,
		arg.AcceptanceCriteria,
		arg.VerificationCommands,
		arg.ExpectedArtifacts,
		arg.RelevantPaths,
		arg.RequiredTools,
		arg.RequiredPermissions,
		arg.Environment,
		arg.Input,
		arg.InputSchema,
		arg.RequiredCapabilities,
		arg.AllowedHarnesses,
		arg.RetryPolicy,
		arg.CreatedBy,
		arg.CreatedByID,
		arg.CreationReason,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.ParentID,
		&i.RootID,
		&i.SourceAttemptID,
		&i.SourceArtifactID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.Tags,
		&i.AcceptanceCriteria,
		&i.VerificationCommands,
		&i.ExpectedArtifacts,
		&i.RelevantPaths,
		&i.RequiredTools,
		&i.RequiredPermissions,
		&i.Environment,
		&i.Input,
		&i.InputSchema,
		&i.RequiredCapabilities,
		&i.AllowedHarnesses,
		&i.RetryPolicy,
		&i.CreatedBy,
		&i.CreatedByID,
		&i.CreationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTicketDependency = `-- name: CreateTicketDependency :one
INSERT INTO ticket_dependencies (
    ticket_id,
    depends_on_ticket_id,
    workspace_id,
    project_id
)
VALUES ($1, $2, $3, $4)
RETURNING ticket_id, depends_on_ticket_id, workspace_id, project_id, created_at
`

type CreateTicketDependencyParams struct {
	TicketID          pgtype.UUID `db:"ticket_id" json:"ticket_id"`
	DependsOnTicketID pgtype.UUID `db:"depends_on_ticket_id" json:"depends_on_ticket_id"`
	WorkspaceID       pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ProjectID         pgtype.UUID `db:"project_id" json:"project_id"`
}

func (q *Queries) CreateTicketDependency(ctx context.Context, arg CreateTicketDependencyParams) (TicketDependency, error) {
	row := q.db.QueryRow(ctx, createTicketDependency,
		arg.TicketID,
		arg.DependsOnTicketID,
		arg.WorkspaceID,
		arg.ProjectID,
	)
	var i TicketDependency
	err := row.Scan(
		&i.TicketID,
		&i.DependsOnTicketID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.CreatedAt,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT id, workspace_id, project_id, parent_id, root_id, source_attempt_id, source_artifact_id, title, description, type, status, priority, tags, acceptance_criteria, verification_commands, expected_artifacts, relevant_paths, required_tools, required_permissions, environment, input, input_schema, required_capabilities, allowed_harnesses, retry_policy, created_by, created_by_id, creation_reason, created_at, updated_at
FROM tickets
WHERE id = $1
`

func (q *Queries) GetTicket(ctx context.Context, id pgtype.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.ParentID,
		&i.RootID,
		&i.SourceAttemptID,
		&i.SourceArtifactID,
		&i.Title,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.Tags,
		&i.AcceptanceCriteria,
		&i.VerificationCommands,
		&i.ExpectedArtifacts,
		&i.RelevantPaths,
		&i.RequiredTools,
		&i.RequiredPermissions,
		&i.Environment,
		&i.Input,
		&i.InputSchema,
		&i.RequiredCapabilities,
		&i.AllowedHarnesses,
		&i.RetryPolicy,
		&i.CreatedBy,
		&i.CreatedByID,
		&i.CreationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTicketDependencies = `-- name: ListTicketDependencies :many
SELECT ticket_id, depends_on_ticket_id, workspace_id, project_id, created_at
FROM ticket_dependencies
WHERE ticket_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListTicketDependencies(ctx context.Context, ticketID pgtype.UUID) ([]TicketDependency, error) {
	rows, err := q.db.Query(ctx, listTicketDependencies, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketDependency{}
	for rows.Next() {
		var i TicketDependency
		if err := rows.Scan(
			&i.TicketID,
			&i.DependsOnTicketID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTickets = `-- name: ListTickets :many
SELECT id, workspace_id, project_id, parent_id, root_id, source_attempt_id, source_artifact_id, title, description, type, status, priority, tags, acceptance_criteria, verification_commands, expected_artifacts, relevant_paths, required_tools, required_permissions, environment, input, input_schema, required_capabilities, allowed_harnesses, retry_policy, created_by, created_by_id, creation_reason, created_at, updated_at
FROM tickets
WHERE workspace_id = $1
  AND project_id = $2
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::text IS NULL OR type = $4::text)
ORDER BY priority ASC, created_at ASC
LIMIT $6::integer
OFFSET $5::integer
`

type ListTicketsParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ProjectID   pgtype.UUID `db:"project_id" json:"project_id"`
	Status      pgtype.Text `db:"status" json:"status"`
	Type        pgtype.Text `db:"type" json:"type"`
	Offset      int32       `db:"offset" json:"offset"`
	Limit       int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTickets,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Status,
		arg.Type,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.ParentID,
			&i.RootID,
			&i.SourceAttemptID,
			&i.SourceArtifactID,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.Priority,
			&i.Tags,
			&i.AcceptanceCriteria,
			&i.VerificationCommands,
			&i.ExpectedArtifacts,
			&i.RelevantPaths,
			&i.RequiredTools,
			&i.RequiredPermissions,
			&i.Environment,
			&i.Input,
			&i.InputSchema,
			&i.RequiredCapabilities,
			&i.AllowedHarnesses,
			&i.RetryPolicy,
			&i.CreatedBy,
			&i.CreatedByID,
			&i.CreationReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
