// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transitions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blockAttempt = `-- name: BlockAttempt :one
WITH updated_attempt AS (
    UPDATE attempts a
    SET status = 'blocked',
        failure_reason = $1::text,
        failure_category = $2::text,
        blocker = $3::jsonb,
        completed_at = $4::timestamptz
    WHERE a.id = $5::uuid
      AND a.status = 'running'
    RETURNING id, workspace_id, project_id, ticket_id, agent_id, harness, model, status, lease_expires_at, last_heartbeat_at, progress_percent, current_summary, next_step, output, output_schema, failure_reason, failure_category, blocker, trace_id, checkpoint_ref, started_at, completed_at
),
updated_ticket AS (
    UPDATE tickets t
    SET status = 'blocked',
        updated_at = now()
    FROM updated_attempt a
    WHERE t.id = a.ticket_id
    RETURNING t.id, t.status
),
blocked_event AS (
    INSERT INTO ticket_events (
        workspace_id,
        project_id,
        ticket_id,
        attempt_id,
        type,
        actor_type,
        actor_id,
        data
    )
    SELECT
        a.workspace_id,
        a.project_id,
        a.ticket_id,
        a.id,
        'blocked',
        'agent',
        a.agent_id,
        jsonb_build_object(
            'ticket_status', t.status,
            'failure_category', a.failure_category
        )
    FROM updated_attempt a
    JOIN updated_ticket t ON t.id = a.ticket_id
    RETURNING id
)
SELECT
    a.id AS attempt_id,
    a.workspace_id,
    a.project_id,
    a.ticket_id,
    a.status AS attempt_status,
    t.status AS ticket_status
FROM updated_attempt a
JOIN updated_ticket t ON t.id = a.ticket_id
`

type BlockAttemptParams struct {
	BlockerReason   string             `db:"blocker_reason" json:"blocker_reason"`
	FailureCategory pgtype.Text        `db:"failure_category" json:"failure_category"`
	Blocker         []byte             `db:"blocker" json:"blocker"`
	CompletedAt     pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	AttemptID       pgtype.UUID        `db:"attempt_id" json:"attempt_id"`
}

type BlockAttemptRow struct {
	AttemptID     pgtype.UUID `db:"attempt_id" json:"attempt_id"`
	WorkspaceID   pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ProjectID     pgtype.UUID `db:"project_id" json:"project_id"`
	TicketID      pgtype.UUID `db:"ticket_id" json:"ticket_id"`
	AttemptStatus string      `db:"attempt_status" json:"attempt_status"`
	TicketStatus  string      `db:"ticket_status" json:"ticket_status"`
}

func (q *Queries) BlockAttempt(ctx context.Context, arg BlockAttemptParams) (BlockAttemptRow, error) {
	row := q.db.QueryRow(ctx, blockAttempt,
		arg.BlockerReason,
		arg.FailureCategory,
		arg.Blocker,
		arg.CompletedAt,
		arg.AttemptID,
	)
	var i BlockAttemptRow
	err := row.Scan(
		&i.AttemptID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TicketID,
		&i.AttemptStatus,
		&i.TicketStatus,
	)
	return i, err
}

const cancelAttempt = `-- name: CancelAttempt :one
WITH updated_attempt AS (
    UPDATE attempts a
    SET status = 'cancelled',
        failure_reason = $1::text,
        completed_at = $2::timestamptz
    WHERE a.id = $3::uuid
      AND a.status = 'running'
    RETURNING id, workspace_id, project_id, ticket_id, agent_id, harness, model, status, lease_expires_at, last_heartbeat_at, progress_percent, current_summary, next_step, output, output_schema, failure_reason, failure_category, blocker, trace_id, checkpoint_ref, started_at, completed_at
),
updated_ticket AS (
    UPDATE tickets t
    SET status = 'todo',
        updated_at = now()
    FROM updated_attempt a
    WHERE t.id = a.ticket_id
    RETURNING t.id, t.status
),
cancelled_event AS (
    INSERT INTO ticket_events (
        workspace_id,
        project_id,
        ticket_id,
        attempt_id,
        type,
        actor_type,
        actor_id,
        data
    )
    SELECT
        a.workspace_id,
        a.project_id,
        a.ticket_id,
        a.id,
        'cancelled',
        'agent',
        a.agent_id,
        jsonb_build_object('ticket_status', t.status)
    FROM updated_attempt a
    JOIN updated_ticket t ON t.id = a.ticket_id
    RETURNING id
)
SELECT
    a.id AS attempt_id,
    a.workspace_id,
    a.project_id,
    a.ticket_id,
    a.status AS attempt_status,
    t.status AS ticket_status
FROM updated_attempt a
JOIN updated_ticket t ON t.id = a.ticket_id
`

type CancelAttemptParams struct {
	Reason      pgtype.Text        `db:"reason" json:"reason"`
	CompletedAt pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	AttemptID   pgtype.UUID        `db:"attempt_id" json:"attempt_id"`
}

type CancelAttemptRow struct {
	AttemptID     pgtype.UUID `db:"attempt_id" json:"attempt_id"`
	WorkspaceID   pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ProjectID     pgtype.UUID `db:"project_id" json:"project_id"`
	TicketID      pgtype.UUID `db:"ticket_id" json:"ticket_id"`
	AttemptStatus string      `db:"attempt_status" json:"attempt_status"`
	TicketStatus  string      `db:"ticket_status" json:"ticket_status"`
}

func (q *Queries) CancelAttempt(ctx context.Context, arg CancelAttemptParams) (CancelAttemptRow, error) {
	row := q.db.QueryRow(ctx, cancelAttempt, arg.Reason, arg.CompletedAt, arg.AttemptID)
	var i CancelAttemptRow
	err := row.Scan(
		&i.AttemptID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TicketID,
		&i.AttemptStatus,
		&i.TicketStatus,
	)
	return i, err
}

const completeAttempt = `-- name: CompleteAttempt :one
WITH updated_attempt AS (
    UPDATE attempts a
    SET status = 'succeeded',
        progress_percent = 100,
        output = $1::jsonb,
        output_schema = $2::text,
        completed_at = $3::timestamptz
    WHERE a.id = $4::uuid
      AND a.status = 'running'
    RETURNING id, workspace_id, project_id, ticket_id, agent_id, harness, model, status, lease_expires_at, last_heartbeat_at, progress_percent, current_summary, next_step, output, output_schema, failure_reason, failure_category, blocker, trace_id, checkpoint_ref, started_at, completed_at
),
updated_ticket AS (
    UPDATE tickets t
    SET status = CASE
            WHEN COALESCE((t.retry_policy->>'requires_review_on_success')::boolean, false)
                THEN 'needs_review'
            ELSE 'done'
        END,
        updated_at = now()
    FROM updated_attempt a
    WHERE t.id = a.ticket_id
    RETURNING t.id, t.status
),
completed_event AS (
    INSERT INTO ticket_events (
        workspace_id,
        project_id,
        ticket_id,
        attempt_id,
        type,
        actor_type,
        actor_id,
        data
    )
    SELECT
        a.workspace_id,
        a.project_id,
        a.ticket_id,
        a.id,
        'completed',
        'agent',
        a.agent_id,
        jsonb_build_object('ticket_status', t.status)
    FROM updated_attempt a
    JOIN updated_ticket t ON t.id = a.ticket_id
    RETURNING id
)
SELECT
    a.id AS attempt_id,
    a.workspace_id,
    a.project_id,
    a.ticket_id,
    a.status AS attempt_status,
    t.status AS ticket_status
FROM updated_attempt a
JOIN updated_ticket t ON t.id = a.ticket_id
`

type CompleteAttemptParams struct {
	Output       []byte             `db:"output" json:"output"`
	OutputSchema pgtype.Text        `db:"output_schema" json:"output_schema"`
	CompletedAt  pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	AttemptID    pgtype.UUID        `db:"attempt_id" json:"attempt_id"`
}

type CompleteAttemptRow struct {
	AttemptID     pgtype.UUID `db:"attempt_id" json:"attempt_id"`
	WorkspaceID   pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ProjectID     pgtype.UUID `db:"project_id" json:"project_id"`
	TicketID      pgtype.UUID `db:"ticket_id" json:"ticket_id"`
	AttemptStatus string      `db:"attempt_status" json:"attempt_status"`
	TicketStatus  string      `db:"ticket_status" json:"ticket_status"`
}

func (q *Queries) CompleteAttempt(ctx context.Context, arg CompleteAttemptParams) (CompleteAttemptRow, error) {
	row := q.db.QueryRow(ctx, completeAttempt,
		arg.Output,
		arg.OutputSchema,
		arg.CompletedAt,
		arg.AttemptID,
	)
	var i CompleteAttemptRow
	err := row.Scan(
		&i.AttemptID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TicketID,
		&i.AttemptStatus,
		&i.TicketStatus,
	)
	return i, err
}

const expireAttempt = `-- name: ExpireAttempt :one
WITH updated_attempt AS (
    UPDATE attempts a
    SET status = 'expired',
        failure_reason = 'lease expired',
        completed_at = $1::timestamptz
    WHERE a.id = $2::uuid
      AND a.status = 'running'
      AND a.lease_expires_at < $3::timestamptz
    RETURNING id, workspace_id, project_id, ticket_id, agent_id, harness, model, status, lease_expires_at, last_heartbeat_at, progress_percent, current_summary, next_step, output, output_schema, failure_reason, failure_category, blocker, trace_id, checkpoint_ref, started_at, completed_at
),
updated_ticket AS (
    UPDATE tickets t
    SET status = CASE
            WHEN (
                SELECT count(*)::integer
                FROM attempts counted_attempts
                WHERE counted_attempts.ticket_id = t.id
                  AND counted_attempts.status IN ('failed', 'expired')
            ) >= COALESCE((t.retry_policy->>'max_attempts')::integer, 3)
                THEN 'failed'
            ELSE 'todo'
        END,
        updated_at = now()
    FROM updated_attempt a
    WHERE t.id = a.ticket_id
    RETURNING t.id, t.status
),
expired_event AS (
    INSERT INTO ticket_events (
        workspace_id,
        project_id,
        ticket_id,
        attempt_id,
        type,
        actor_type,
        actor_id,
        data
    )
    SELECT
        a.workspace_id,
        a.project_id,
        a.ticket_id,
        a.id,
        'expired',
        'system',
        a.agent_id,
        jsonb_build_object('ticket_status', t.status)
    FROM updated_attempt a
    JOIN updated_ticket t ON t.id = a.ticket_id
    RETURNING id
)
SELECT
    a.id AS attempt_id,
    a.workspace_id,
    a.project_id,
    a.ticket_id,
    a.status AS attempt_status,
    t.status AS ticket_status
FROM updated_attempt a
JOIN updated_ticket t ON t.id = a.ticket_id
`

type ExpireAttemptParams struct {
	CompletedAt      pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	AttemptID        pgtype.UUID        `db:"attempt_id" json:"attempt_id"`
	ExpirationCutoff pgtype.Timestamptz `db:"expiration_cutoff" json:"expiration_cutoff"`
}

type ExpireAttemptRow struct {
	AttemptID     pgtype.UUID `db:"attempt_id" json:"attempt_id"`
	WorkspaceID   pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ProjectID     pgtype.UUID `db:"project_id" json:"project_id"`
	TicketID      pgtype.UUID `db:"ticket_id" json:"ticket_id"`
	AttemptStatus string      `db:"attempt_status" json:"attempt_status"`
	TicketStatus  string      `db:"ticket_status" json:"ticket_status"`
}

func (q *Queries) ExpireAttempt(ctx context.Context, arg ExpireAttemptParams) (ExpireAttemptRow, error) {
	row := q.db.QueryRow(ctx, expireAttempt, arg.CompletedAt, arg.AttemptID, arg.ExpirationCutoff)
	var i ExpireAttemptRow
	err := row.Scan(
		&i.AttemptID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TicketID,
		&i.AttemptStatus,
		&i.TicketStatus,
	)
	return i, err
}

const failAttempt = `-- name: FailAttempt :one
WITH updated_attempt AS (
    UPDATE attempts a
    SET status = 'failed',
        failure_reason = $1::text,
        failure_category = $2::text,
        output = $3::jsonb,
        completed_at = $4::timestamptz
    WHERE a.id = $5::uuid
      AND a.status = 'running'
    RETURNING id, workspace_id, project_id, ticket_id, agent_id, harness, model, status, lease_expires_at, last_heartbeat_at, progress_percent, current_summary, next_step, output, output_schema, failure_reason, failure_category, blocker, trace_id, checkpoint_ref, started_at, completed_at
),
updated_ticket AS (
    UPDATE tickets t
    SET status = CASE
            WHEN COALESCE(t.retry_policy->>'on_failure', 'return_to_todo') = 'mark_failed'
                THEN 'failed'
            WHEN COALESCE(t.retry_policy->>'on_failure', 'return_to_todo') = 'needs_review'
                THEN 'needs_review'
            WHEN (
                SELECT count(*)::integer
                FROM attempts counted_attempts
                WHERE counted_attempts.ticket_id = t.id
                  AND counted_attempts.status IN ('failed', 'expired')
            ) >= COALESCE((t.retry_policy->>'max_attempts')::integer, 3)
                THEN 'failed'
            ELSE 'todo'
        END,
        updated_at = now()
    FROM updated_attempt a
    WHERE t.id = a.ticket_id
    RETURNING t.id, t.status
),
failed_event AS (
    INSERT INTO ticket_events (
        workspace_id,
        project_id,
        ticket_id,
        attempt_id,
        type,
        actor_type,
        actor_id,
        data
    )
    SELECT
        a.workspace_id,
        a.project_id,
        a.ticket_id,
        a.id,
        'failed',
        'agent',
        a.agent_id,
        jsonb_build_object(
            'ticket_status', t.status,
            'failure_category', a.failure_category
        )
    FROM updated_attempt a
    JOIN updated_ticket t ON t.id = a.ticket_id
    RETURNING id
)
SELECT
    a.id AS attempt_id,
    a.workspace_id,
    a.project_id,
    a.ticket_id,
    a.status AS attempt_status,
    t.status AS ticket_status
FROM updated_attempt a
JOIN updated_ticket t ON t.id = a.ticket_id
`

type FailAttemptParams struct {
	FailureReason   string             `db:"failure_reason" json:"failure_reason"`
	FailureCategory pgtype.Text        `db:"failure_category" json:"failure_category"`
	Output          []byte             `db:"output" json:"output"`
	CompletedAt     pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	AttemptID       pgtype.UUID        `db:"attempt_id" json:"attempt_id"`
}

type FailAttemptRow struct {
	AttemptID     pgtype.UUID `db:"attempt_id" json:"attempt_id"`
	WorkspaceID   pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ProjectID     pgtype.UUID `db:"project_id" json:"project_id"`
	TicketID      pgtype.UUID `db:"ticket_id" json:"ticket_id"`
	AttemptStatus string      `db:"attempt_status" json:"attempt_status"`
	TicketStatus  string      `db:"ticket_status" json:"ticket_status"`
}

func (q *Queries) FailAttempt(ctx context.Context, arg FailAttemptParams) (FailAttemptRow, error) {
	row := q.db.QueryRow(ctx, failAttempt,
		arg.FailureReason,
		arg.FailureCategory,
		arg.Output,
		arg.CompletedAt,
		arg.AttemptID,
	)
	var i FailAttemptRow
	err := row.Scan(
		&i.AttemptID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TicketID,
		&i.AttemptStatus,
		&i.TicketStatus,
	)
	return i, err
}
