// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingWebhookDeliveries = `-- name: ClaimPendingWebhookDeliveries :many
WITH candidates AS (
    SELECT d.id
    FROM webhook_deliveries d
    JOIN webhook_subscriptions s ON s.id = d.subscription_id
    WHERE s.active
      AND d.status IN ('pending', 'delivering')
      AND d.attempt_count < d.max_attempts
      AND d.next_attempt_at <= $2::timestamptz
      AND (
          d.status <> 'delivering'
          OR d.locked_until IS NULL
          OR d.locked_until <= $2::timestamptz
      )
    ORDER BY d.created_at ASC
    LIMIT $3::integer
    FOR UPDATE OF d SKIP LOCKED
)
UPDATE webhook_deliveries d
SET status = 'delivering',
    locked_until = $1::timestamptz,
    updated_at = now()
FROM candidates c
JOIN webhook_deliveries claimed ON claimed.id = c.id
JOIN webhook_subscriptions s ON s.id = claimed.subscription_id AND s.active
WHERE d.id = c.id
RETURNING
    d.id,
    d.subscription_id,
    d.event_id,
    d.workspace_id,
    d.project_id,
    d.ticket_id,
    d.attempt_id,
    d.status,
    d.payload,
    d.attempt_count,
    d.max_attempts,
    d.next_attempt_at,
    d.locked_until,
    d.last_attempt_at,
    d.delivered_at,
    d.response_status,
    d.response_body,
    d.error,
    d.created_at,
    d.updated_at,
    s.endpoint_url,
    s.secret
`

type ClaimPendingWebhookDeliveriesParams struct {
	LockedUntil pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
	Now         pgtype.Timestamptz `db:"now" json:"now"`
	BatchLimit  int32              `db:"batch_limit" json:"batch_limit"`
}

type ClaimPendingWebhookDeliveriesRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	SubscriptionID pgtype.UUID        `db:"subscription_id" json:"subscription_id"`
	EventID        pgtype.UUID        `db:"event_id" json:"event_id"`
	WorkspaceID    pgtype.UUID        `db:"workspace_id" json:"workspace_id"`
	ProjectID      pgtype.UUID        `db:"project_id" json:"project_id"`
	TicketID       pgtype.UUID        `db:"ticket_id" json:"ticket_id"`
	AttemptID      pgtype.UUID        `db:"attempt_id" json:"attempt_id"`
	Status         string             `db:"status" json:"status"`
	Payload        []byte             `db:"payload" json:"payload"`
	AttemptCount   int32              `db:"attempt_count" json:"attempt_count"`
	MaxAttempts    int32              `db:"max_attempts" json:"max_attempts"`
	NextAttemptAt  pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	LockedUntil    pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
	LastAttemptAt  pgtype.Timestamptz `db:"last_attempt_at" json:"last_attempt_at"`
	DeliveredAt    pgtype.Timestamptz `db:"delivered_at" json:"delivered_at"`
	ResponseStatus pgtype.Int4        `db:"response_status" json:"response_status"`
	ResponseBody   pgtype.Text        `db:"response_body" json:"response_body"`
	Error          pgtype.Text        `db:"error" json:"error"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	EndpointUrl    string             `db:"endpoint_url" json:"endpoint_url"`
	Secret         pgtype.Text        `db:"secret" json:"secret"`
}

func (q *Queries) ClaimPendingWebhookDeliveries(ctx context.Context, arg ClaimPendingWebhookDeliveriesParams) ([]ClaimPendingWebhookDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, claimPendingWebhookDeliveries, arg.LockedUntil, arg.Now, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimPendingWebhookDeliveriesRow{}
	for rows.Next() {
		var i ClaimPendingWebhookDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.EventID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.TicketID,
			&i.AttemptID,
			&i.Status,
			&i.Payload,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.LockedUntil,
			&i.LastAttemptAt,
			&i.DeliveredAt,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EndpointUrl,
			&i.Secret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWebhookSubscription = `-- name: CreateWebhookSubscription :one
INSERT INTO webhook_subscriptions (
    workspace_id,
    project_id,
    endpoint_url,
    secret,
    event_types,
    active,
    max_attempts,
    description
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, workspace_id, project_id, endpoint_url, secret, event_types, active, max_attempts, description, created_at, updated_at
`

type CreateWebhookSubscriptionParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ProjectID   pgtype.UUID `db:"project_id" json:"project_id"`
	EndpointUrl string      `db:"endpoint_url" json:"endpoint_url"`
	Secret      pgtype.Text `db:"secret" json:"secret"`
	EventTypes  []string    `db:"event_types" json:"event_types"`
	Active      bool        `db:"active" json:"active"`
	MaxAttempts int32       `db:"max_attempts" json:"max_attempts"`
	Description string      `db:"description" json:"description"`
}

func (q *Queries) CreateWebhookSubscription(ctx context.Context, arg CreateWebhookSubscriptionParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, createWebhookSubscription,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.EndpointUrl,
		arg.Secret,
		arg.EventTypes,
		arg.Active,
		arg.MaxAttempts,
		arg.Description,
	)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.EndpointUrl,
		&i.Secret,
		&i.EventTypes,
		&i.Active,
		&i.MaxAttempts,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWebhookDeliveriesByEvent = `-- name: ListWebhookDeliveriesByEvent :many
SELECT id, subscription_id, event_id, workspace_id, project_id, ticket_id, attempt_id, status, payload, attempt_count, max_attempts, next_attempt_at, locked_until, last_attempt_at, delivered_at, response_status, response_body, error, created_at, updated_at
FROM webhook_deliveries
WHERE event_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListWebhookDeliveriesByEvent(ctx context.Context, eventID pgtype.UUID) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.EventID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.TicketID,
			&i.AttemptID,
			&i.Status,
			&i.Payload,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.LockedUntil,
			&i.LastAttemptAt,
			&i.DeliveredAt,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookDeliveryFailed = `-- name: MarkWebhookDeliveryFailed :one
UPDATE webhook_deliveries
SET status = CASE
        WHEN $1::integer >= max_attempts THEN 'failed'
        ELSE 'pending'
    END,
    attempt_count = $1::integer,
    locked_until = NULL,
    last_attempt_at = $2::timestamptz,
    response_status = $3::integer,
    response_body = $4::text,
    error = $5::text,
    next_attempt_at = $6::timestamptz,
    updated_at = now()
WHERE id = $7::uuid
RETURNING id, subscription_id, event_id, workspace_id, project_id, ticket_id, attempt_id, status, payload, attempt_count, max_attempts, next_attempt_at, locked_until, last_attempt_at, delivered_at, response_status, response_body, error, created_at, updated_at
`

type MarkWebhookDeliveryFailedParams struct {
	AttemptCount   int32              `db:"attempt_count" json:"attempt_count"`
	AttemptedAt    pgtype.Timestamptz `db:"attempted_at" json:"attempted_at"`
	ResponseStatus pgtype.Int4        `db:"response_status" json:"response_status"`
	ResponseBody   pgtype.Text        `db:"response_body" json:"response_body"`
	Error          string             `db:"error" json:"error"`
	NextAttemptAt  pgtype.Timestamptz `db:"next_attempt_at" json:"next_attempt_at"`
	ID             pgtype.UUID        `db:"id" json:"id"`
}

func (q *Queries) MarkWebhookDeliveryFailed(ctx context.Context, arg MarkWebhookDeliveryFailedParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, markWebhookDeliveryFailed,
		arg.AttemptCount,
		arg.AttemptedAt,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.Error,
		arg.NextAttemptAt,
		arg.ID,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.EventID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TicketID,
		&i.AttemptID,
		&i.Status,
		&i.Payload,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.LastAttemptAt,
		&i.DeliveredAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWebhookDeliverySucceeded = `-- name: MarkWebhookDeliverySucceeded :one
UPDATE webhook_deliveries
SET status = 'succeeded',
    attempt_count = $1::integer,
    locked_until = NULL,
    last_attempt_at = $2::timestamptz,
    delivered_at = $2::timestamptz,
    response_status = $3::integer,
    response_body = $4::text,
    error = NULL,
    updated_at = now()
WHERE id = $5::uuid
RETURNING id, subscription_id, event_id, workspace_id, project_id, ticket_id, attempt_id, status, payload, attempt_count, max_attempts, next_attempt_at, locked_until, last_attempt_at, delivered_at, response_status, response_body, error, created_at, updated_at
`

type MarkWebhookDeliverySucceededParams struct {
	AttemptCount   int32              `db:"attempt_count" json:"attempt_count"`
	AttemptedAt    pgtype.Timestamptz `db:"attempted_at" json:"attempted_at"`
	ResponseStatus pgtype.Int4        `db:"response_status" json:"response_status"`
	ResponseBody   pgtype.Text        `db:"response_body" json:"response_body"`
	ID             pgtype.UUID        `db:"id" json:"id"`
}

func (q *Queries) MarkWebhookDeliverySucceeded(ctx context.Context, arg MarkWebhookDeliverySucceededParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, markWebhookDeliverySucceeded,
		arg.AttemptCount,
		arg.AttemptedAt,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.ID,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.EventID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TicketID,
		&i.AttemptID,
		&i.Status,
		&i.Payload,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.LockedUntil,
		&i.LastAttemptAt,
		&i.DeliveredAt,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
