// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (workspace_id, name)
VALUES ($1, $2)
RETURNING id, workspace_id, name, created_at, updated_at
`

type CreateProjectParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	Name        string      `db:"name" json:"name"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.WorkspaceID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateWorkspace(ctx context.Context, name string) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkspaceMember = `-- name: DeleteWorkspaceMember :exec
DELETE FROM workspace_members
WHERE workspace_id = $1
  AND actor_type = $2
  AND actor_id = $3
`

type DeleteWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ActorType   string      `db:"actor_type" json:"actor_type"`
	ActorID     string      `db:"actor_id" json:"actor_id"`
}

func (q *Queries) DeleteWorkspaceMember(ctx context.Context, arg DeleteWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceMember, arg.WorkspaceID, arg.ActorType, arg.ActorID)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, workspace_id, name, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, created_at, updated_at
FROM workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id pgtype.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByWorkspace = `-- name: ListProjectsByWorkspace :many
SELECT id, workspace_id, name, created_at, updated_at
FROM projects
WHERE workspace_id = $1
ORDER BY name ASC
`

func (q *Queries) ListProjectsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT workspace_id, actor_type, actor_id, role, created_at, updated_at
FROM workspace_members
WHERE workspace_id = $1
ORDER BY
    CASE role
        WHEN 'owner' THEN 1
        WHEN 'admin' THEN 2
        WHEN 'member' THEN 3
        WHEN 'viewer' THEN 4
        ELSE 5
    END,
    actor_type ASC,
    actor_id ASC
`

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID pgtype.UUID) ([]WorkspaceMember, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceMember{}
	for rows.Next() {
		var i WorkspaceMember
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ActorType,
			&i.ActorID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, name, created_at, updated_at
FROM workspaces
ORDER BY name ASC
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspaceMemberRole = `-- name: UpdateWorkspaceMemberRole :one
UPDATE workspace_members
SET role = $4, updated_at = now()
WHERE workspace_id = $1
  AND actor_type = $2
  AND actor_id = $3
RETURNING workspace_id, actor_type, actor_id, role, created_at, updated_at
`

type UpdateWorkspaceMemberRoleParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ActorType   string      `db:"actor_type" json:"actor_type"`
	ActorID     string      `db:"actor_id" json:"actor_id"`
	Role        string      `db:"role" json:"role"`
}

func (q *Queries) UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceMemberRole,
		arg.WorkspaceID,
		arg.ActorType,
		arg.ActorID,
		arg.Role,
	)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.ActorType,
		&i.ActorID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWorkspaceMember = `-- name: UpsertWorkspaceMember :one
INSERT INTO workspace_members (workspace_id, actor_type, actor_id, role)
VALUES ($1, $2, $3, $4)
ON CONFLICT (workspace_id, actor_type, actor_id)
DO UPDATE SET role = EXCLUDED.role, updated_at = now()
RETURNING workspace_id, actor_type, actor_id, role, created_at, updated_at
`

type UpsertWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID `db:"workspace_id" json:"workspace_id"`
	ActorType   string      `db:"actor_type" json:"actor_type"`
	ActorID     string      `db:"actor_id" json:"actor_id"`
	Role        string      `db:"role" json:"role"`
}

func (q *Queries) UpsertWorkspaceMember(ctx context.Context, arg UpsertWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, upsertWorkspaceMember,
		arg.WorkspaceID,
		arg.ActorType,
		arg.ActorID,
		arg.Role,
	)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.ActorType,
		&i.ActorID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
